(define (append-inf s-inf t-inf)
  (let loop ([s? #t] [s-inf s-inf] [t-inf t-inf])
    (cond
      ((pair? s-inf)
       (cons (car s-inf)
         (loop s? (cdr s-inf) t-inf)))
      ((null? s-inf) t-inf)
      (s? (loop #f t-inf s-inf))
      (else (lambda ()
              (append-inf (t-inf) (s-inf)))))))